### ISSUE TITLE
The piece won't be moved even if the location is in legal_moves

### ISSUE THREAD

**Issue by freestylofil** [barthap/inpg-checkers#9]
Print commands prompt correct possible squares, yet the if statement (mouse clicked legal move square) still is False

**Comment by barthap** [comment]
You have type mismatch. I think we should unify method return types, because:
- `Board.squares_in_dir()` returns tuple `(x,y)` - OK
- `Board.move_possible_squares()` returns list of coords `(x,y)` OK
- `Board.hop_possible_squares()` returns list of coords `(x,y)` OK
- `Board.legal_moves` concatentates both functions above

But in `GameScene.move_piece()`, _line 42_ you are trying to compare `Square` to tuple `(x,y)`:
```python
if mouse_square in self.board.legal_moves(self.selected_square.location):
```

**Comment by barthap** [comment]
If you added `location` property to `Square` class, just use it
